before_install:
   - sudo apt-get update
   - sudo apt-get install libicu-dev libmozjs-dev
before_script: ./bootstrap && ./configure
script: make distcheck
language: erlang
otp_release:
   - 23.0
   - 22.0
   - 21.0
   - 20.0
   - 19.0
